// Database types generated from Supabase schema
// This file will be auto-generated by Supabase CLI in production
// For now, we'll define the core types manually

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export type UserRole = 'admin' | 'manager' | 'guard' | 'resident' | 'owner' | 'tenant';
export type VisitorType = 'expected' | 'walk-in' | 'delivery' | 'service' | 'guest';
export type VisitorStatus = 'pending' | 'approved' | 'checked-in' | 'checked-out' | 'denied';
export type IssueCategory = 'plumbing' | 'electrical' | 'cleaning' | 'security' | 'maintenance' | 'parking' | 'noise' | 'other';
export type IssuePriority = 'low' | 'medium' | 'high' | 'urgent';
export type IssueStatus = 'open' | 'in-progress' | 'resolved' | 'closed' | 'rejected';
export type AnnouncementTarget = 'all' | 'block' | 'unit' | 'role';

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string;
                    phone: string;
                    full_name: string | null;
                    email: string | null;
                    avatar_url: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id: string;
                    phone: string;
                    full_name?: string | null;
                    email?: string | null;
                    avatar_url?: string | null;
                };
                Update: {
                    phone?: string;
                    full_name?: string | null;
                    email?: string | null;
                    avatar_url?: string | null;
                };
            };
            user_roles: {
                Row: {
                    id: string;
                    user_id: string;
                    society_id: string;
                    role: UserRole;
                    unit_id: string | null;
                    is_active: boolean;
                    assigned_at: string;
                    assigned_by: string | null;
                };
                Insert: {
                    user_id: string;
                    society_id: string;
                    role: UserRole;
                    unit_id?: string | null;
                    is_active?: boolean;
                    assigned_by?: string | null;
                };
                Update: {
                    role?: UserRole;
                    unit_id?: string | null;
                    is_active?: boolean;
                };
            };
            societies: {
                Row: {
                    id: string;
                    name: string;
                    address: string | null;
                    city: string | null;
                    state: string | null;
                    pincode: string | null;
                    total_units: number;
                    settings: Json;
                    created_by: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    name: string;
                    address?: string | null;
                    city?: string | null;
                    state?: string | null;
                    pincode?: string | null;
                    total_units?: number;
                    settings?: Json;
                    created_by?: string | null;
                };
                Update: {
                    name?: string;
                    address?: string | null;
                    settings?: Json;
                };
            };
            visitors: {
                Row: {
                    id: string;
                    society_id: string;
                    unit_id: string | null;
                    host_id: string | null;
                    visitor_name: string;
                    visitor_phone: string | null;
                    visitor_photo_url: string | null;
                    vehicle_number: string | null;
                    visitor_type: VisitorType;
                    purpose: string | null;
                    expected_date: string | null;
                    expected_time: string | null;
                    status: VisitorStatus;
                    checked_in_at: string | null;
                    checked_in_by: string | null;
                    checked_out_at: string | null;
                    checked_out_by: string | null;
                    otp: string | null;
                    otp_expires_at: string | null;
                    qr_code: string | null;
                    is_recurring: boolean;
                    recurrence_pattern: string | null;
                    valid_until: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    society_id: string;
                    unit_id?: string | null;
                    host_id?: string | null;
                    visitor_name: string;
                    visitor_phone?: string | null;
                    visitor_type?: VisitorType;
                    purpose?: string | null;
                    expected_date?: string | null;
                    expected_time?: string | null;
                    status?: VisitorStatus;
                };
                Update: {
                    status?: VisitorStatus;
                    checked_in_at?: string | null;
                    checked_in_by?: string | null;
                    checked_out_at?: string | null;
                    checked_out_by?: string | null;
                };
            };
            issues: {
                Row: {
                    id: string;
                    society_id: string;
                    unit_id: string | null;
                    reported_by: string;
                    title: string;
                    description: string | null;
                    category: IssueCategory;
                    priority: IssuePriority;
                    status: IssueStatus;
                    photos: string[] | null;
                    assigned_to: string | null;
                    assigned_at: string | null;
                    resolved_at: string | null;
                    resolved_by: string | null;
                    resolution_notes: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    society_id: string;
                    unit_id?: string | null;
                    reported_by: string;
                    title: string;
                    description?: string | null;
                    category: IssueCategory;
                    priority?: IssuePriority;
                    photos?: string[] | null;
                };
                Update: {
                    status?: IssueStatus;
                    assigned_to?: string | null;
                    resolution_notes?: string | null;
                };
            };
            announcements: {
                Row: {
                    id: string;
                    society_id: string;
                    title: string;
                    message: string;
                    attachments: string[] | null;
                    target_type: AnnouncementTarget;
                    target_block_id: string | null;
                    target_unit_id: string | null;
                    target_role: UserRole | null;
                    created_by: string;
                    created_at: string;
                    expires_at: string | null;
                };
                Insert: {
                    society_id: string;
                    title: string;
                    message: string;
                    attachments?: string[] | null;
                    target_type?: AnnouncementTarget;
                    target_block_id?: string | null;
                    target_unit_id?: string | null;
                    target_role?: UserRole | null;
                    created_by: string;
                    expires_at?: string | null;
                };
                Update: {
                    title?: string;
                    message?: string;
                };
            };
        };
        Views: {
            [_ in never]: never;
        };
        Functions: {
            [_ in never]: never;
        };
        Enums: {
            user_role: UserRole;
            visitor_type: VisitorType;
            visitor_status: VisitorStatus;
            issue_category: IssueCategory;
            issue_priority: IssuePriority;
            issue_status: IssueStatus;
            announcement_target: AnnouncementTarget;
        };
    };
}
